### ISSUE TITLE
ruTorrent stops populating Added/Finished time

### ISSUE THREAD

**Issue by phene** [Novik/ruTorrent#2227]
Resurrecting same issue from https://github.com/Novik/ruTorrent/issues/1731 and https://github.com/Novik/ruTorrent/issues/1879 because it's still an ongoing issue for many people with no clear resolution.

Suggestions for temporary fixing include:
- Changing the timestamp format??
- Disabling and re-enabling the seedingtime plugin.
- Restarting rtorrent and php

None of these consistently address the issue.

I just wish I had a consistent way to triggering this in order to provide logs or anything else for debugging

**Comment by derailius** [comment]
same issue here with 3.10

**Comment by n1ce-0ne** [comment]
im still using v3.7 installed about 5 years ago, its very random on mine, only a couple then starts working again,
from the comments ive seen about it on here i feel its got worse in the later versions where its more than a couple.
would be nice to see this fixed in the new v4, maybe @stickz could take a look after hes finished working his magic on the rest of the code ❤

**Comment by ranirahn** [comment]
I have tried to get Added time working for so long. Tried to change user that runs rtorrent and rutorrent. Figured maybe its some rights issue. Still nothing. Then i did chmod 777 for session AND data folders and then all working. I really dont get why this works if everything have been run with same user. I really dont want to do that chmod 777 for these folders every time i restart rtorrent or rutorrent.

**Comment by Novik** [comment]
https://github.com/Novik/ruTorrent/issues/2088#issuecomment-674539700

**Comment by ranirahn** [comment]
> [#2088 (comment)](https://github.com/Novik/ruTorrent/issues/2088#issuecomment-674539700)

I already did that. Recompiled and still have this problem.

After restarting rtorrent and apache i only need chmod 777 to session folder and added time is there. At least dont need to 777 the data itself. But i still dont see a reason. Only file that get changed is rtorrent.lock file. Everything new get reverted back to 666 so why dont work 777 only on rtorrent.lock file. But after doing 777 to session folder it suddenly works. Makes no sense what so ever.
